ip: localhost
port: 1883
trigger_topic: "indonesia/inference/trigger"
image_topic: "indonesia/camera/image"
trigger_time_topic: "indonesia/camera/trigger_time"
message: null


camera_type: flir
trigger_type: external
buffer_size: 0

is_archived: "true"
archive_directory: "save_dir"
archive_parameters:
  archive_freq: "daily"
  archive_storage: 50 # GB
  archive_days: 30 # days